### ISSUE TITLE
filter with limit seems not work

### ISSUE THREAD

**Issue by nyrf** [polymny/ergol#1]
```rust
let users = User::select().filter(user::age::eq(28)).limit(1).execute(&client).await?;
```
```
postgres_1  | 2021-02-19 19:54:07.319 UTC [1621] ERROR:  syntax error at or near "WHERE" at character 29
postgres_1  | 2021-02-19 19:54:07.319 UTC [1621] STATEMENT:  SELECT * FROM users LIMIT 1 WHERE age = $1;
```

**Comment by tforgione** [comment]
Nice catch, there was a problem in the order of the parts in the SQL request.

Fixed in the dev branch, thanks for opening this issue !

**Comment by nyrf** [comment]
Thanks for your great work, any plan to add more query methods like `order_by` and `offset`?

**Comment by tforgione** [comment]
I guess `order_by` and `offset` would not be too difficult to implement, but having a complete thing that exposes everything possible in SQL systems would be much more difficult. If you specifically need a few things (like `order_by` or `offset`), feel free to open issues and I'll implement them, or if you feel brave enough, you could even do a PR. Having a complete query builder is probably not going to happen soon though.

**Comment by nyrf** [comment]
I see. Thank you.
